Elcodi\Component\Page\Entity\Page:
    type: entity
    repositoryClass: Elcodi\Component\Page\Repository\PageRepository
    table: page
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: true
            unique: true
        title:
            column: title
            type: string
            length: 255
            nullable: false
        content:
            column: content
            type: text
            nullable: false
        type:
            column: type
            type: integer
            nullable: false
        path:
            column: path
            type: string
            length: 255
            nullable: true
        publicationDate:
            column: publication_date
            type: datetime
            nullable: true
        persistent:
            column: persistent
            type: boolean
        author:
            column: author
            type: string
            length: 255
            nullable: true
        alternativeUrls:
            column: alternative_urls
            type: array
            nullable: false
        tags:
            column: tags
            type: string
            length: 255
            nullable: true
        specialWords:
            column: special_words
            type: string
            nullable: true
            unique: false
        metaTitle:
            column: meta_title
            type: string
            length: 255
            nullable: true
        metaDescription:
            column: meta_description
            type: string
            length: 255
            nullable: true
        imagesSort:
            column: images_sort
            type: string
            length: 2048
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        enabled:
            column: enabled
            type: boolean

    manyToOne:
        principalImage:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            cascade: ["remove"]
            joinColumn:
                onDelete: SET NULL
                name: principal_image_id
                referencedColumnName: id
                nullable: true
        createdBy:
            targetEntity: Elcodi\Component\User\Entity\Interfaces\AdminUserInterface
            joinColumn:
                onDelete: SET NULL
                name: created_by_admin_user_id
                referencedColumnName: id
                nullable: true
        updatedBy:
            targetEntity: Elcodi\Component\User\Entity\Interfaces\AdminUserInterface
            joinColumn:
                onDelete: SET NULL
                name: updated_by_admin_user_id
                referencedColumnName: id
                nullable: true

    manyToMany:

        images:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            cascade: ["remove"]
            joinTable:
                name: page_image
                joinColumns:
                    page_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
                inverseJoinColumns:
                    image_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
        stores:
            targetEntity: Elcodi\Component\Store\Entity\Interfaces\StoreInterface
            joinTable:
                name: page_store
                joinColumns:
                    page_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
                inverseJoinColumns:
                    store_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
