language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: $SYMFONY_VERSION="^3.0.0"

before_install:
  - composer self-update
  - composer config preferred-install source
  - 'if [[ -n "$GH_TOKEN" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;'
  - 'if [[ -n "$GH_TOKEN" ]]; then composer config preferred-install dist; fi;'
  - 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi;'

install: composer install --no-interaction --no-progress

script: vendor/bin/phpunit -v

after_success:
  - 'if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" && $TRAVIS_PHP_VERSION == "5.6" ]]; then sh generate-api.sh; fi;'

notifications:
  email: false
