services:

    #
    # Factories
    #

    #
    # Factory for entity store
    #
    elcodi.factory.store:
        class: Elcodi\Component\Store\Factory\StoreFactory
        arguments:
            - "@elcodi.factory.address"
        calls:
            - [setEntityNamespace, ["%elcodi.entity.store.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]
