services:

    #
    # Services
    #
    elcodi.wrapper.store:
        class: Elcodi\Component\Store\Wrapper\StoreWrapper
        lazy: true
        arguments:
            - '@request_stack'
            - '@elcodi.repository.store'

    elcodi.store:
        class: Elcodi\Component\Store\Entity\Interfaces\StoreInterface
        lazy: true
        factory:
            - '@elcodi.wrapper.store'
            - get

    elcodi.store_uses_stock:
        class: StdClass
        factory:
            - '@elcodi.store'
            - getUseStock

    elcodi.store_tracker:
        class: StdClass
        factory:
            - '@elcodi.store'
            - getTracker

    elcodi.store_address:
        class: %elcodi.entity.address.class%
        lazy: true
        factory:
            - '@elcodi.store'
            - getAddress

    elcodi.store_template_hash:
        class: StdClass
        factory:
            - '@elcodi.store'
            - getTemplate

    elcodi.store_template:
        class: Elcodi\Component\Plugin\Entity\Plugin
        lazy: true
        factory:
            - '@elcodi.repository.plugin'
            - findOneBy
        arguments:
            - { hash: '@elcodi.store_template_hash' }

    elcodi.store_template_bundle:
        class: StdClass
        factory:
            - '@elcodi.store_template'
            - getBundleName
