services:

    #
    # Transformers
    #
    elcodi.transformer.location_to_location_data:
        class: Elcodi\Component\Geo\Transformer\LocationToLocationDataTransformer
        arguments:
            - '@elcodi.factory.location_data'

    elcodi.transformer.locations_to_string:
        class: Elcodi\Component\Geo\Transformer\LocationsToString
        arguments:
            - '@elcodi.location_provider'