Elcodi\Component\Store\Entity\Store:
    type: entity
    repositoryClass: Elcodi\Component\Store\Repository\StoreRepository
    table: store

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        leitmotiv:
            column: leitmotiv
            type: string
            length: 255
            nullable: true
        code:
            column: code
            type: string
            length: 255
            nullable: true
        email:
            column: email
            type: string
            length: 255
            nullable: true
        isCompany:
            column: is_company
            type: boolean
        cif:
            column: cif
            type: string
            length: 255
            nullable: true
        tracker:
            column: tracker
            type: string
            length: 255
            nullable: true
        template:
            column: template
            type: string
            length: 255
            nullable: true
        useStock:
            column: use_stock
            type: boolean
        domains:
            column: domains
            type: string
            nullable: true
        metaTitle:
            column: meta_title
            type: string
            length: 255
            nullable: true
        metaDescription:
            column: meta_description
            type: string
            length: 255
            nullable: true
        metaKeywords:
            column: meta_keywords
            type: string
            length: 255
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        enabled:
            column: enabled
            type: boolean
            nullable: false

    manyToOne:
        address:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\AddressInterface
            joinColumn:
                name: address_id
                referencedColumnName: id
                nullable: true

    oneToOne:
        logo:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinColumn:
                name: logo_id
                referencedColumnName: id
                nullable: true
        secondaryLogo:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinColumn:
                name: secondary_logo_id
                referencedColumnName: id
                nullable: true
        mobileLogo:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinColumn:
                name: mobile_logo_id
                referencedColumnName: id
                nullable: true
        headerImage:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinColumn:
                name: header_image_id
                referencedColumnName: id
                nullable: true
        backgroundImage:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinColumn:
                name: background_image_id
                referencedColumnName: id
                nullable: true

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
