services:

    #
    # Providers
    #
    elcodi.mapping_provider:
        class: Elcodi\Component\Core\Services\MappingProvider
        arguments:
            - %elcodi.mapping_implementations%

    elcodi.referrer_provider:
        class: Elcodi\Component\Core\Services\ReferrerProvider
        arguments:
            - '@session'
            - '@request_stack'
