Elcodi\Component\User\Entity\AbstractUser:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        email:
            - Email: ~
            - NotBlank: ~
            - NotNull: ~
