Elcodi\Component\Banner\Entity\Banner:
    type: entity
    repositoryClass: Elcodi\Component\Banner\Repository\BannerRepository
    table: banner
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        description:
            column: description
            type: text
            nullable: true
        extra:
            column: extra
            type: string
            length: 255
            nullable: true
        url:
            column: url
            type: string
            length: 255
            nullable: true
        buttonText:
            column: button_text
            type: string
            length: 255
            nullable: true
        newTab:
            column: new_tab
            type: boolean
            nullable: true
        fullWidth:
            column: full_width
            type: boolean
            nullable: true
        special:
            column: special
            type: boolean
            nullable: true
        enabled:
            column: enabled
            type: boolean
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            nullable: false
        updatedAt:
            column: updated_at
            type: datetime
            nullable: false

    manyToMany:
        bannerZones:
            targetEntity: Elcodi\Component\Banner\Entity\Interfaces\BannerZoneInterface
            inversedBy: banners
            joinTable:
                name: banner_banner_zone
                joinColumns:
                    banner_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    banner_zone_id:
                        referencedColumnName: id

    manyToOne:
        principalImage:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            cascade: ["remove"]
            joinColumn:
                name: principal_image_id
                referencedColumnName: id
                nullable: true
        mobileImage:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            cascade: ["remove"]
            joinColumn:
                name: mobile_image_id
                referencedColumnName: id
                nullable: true

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]