Elcodi\Component\Banner\Entity\BannerZone:
    type: entity
    repositoryClass: Elcodi\Component\Banner\Repository\BannerZoneRepository
    table: banner_zone
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
            unique: true
        code:
            column: code
            type: string
            length: 255
            nullable: false
            unique: true
        bannersSort:
            column: banners_sort
            type: string
            length: 2048
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            nullable: false
        updatedAt:
            column: updated_at
            type: datetime
            nullable: false

    manyToMany:
        banners:
            targetEntity: Elcodi\Component\Banner\Entity\Interfaces\BannerInterface
            mappedBy: bannerZones

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]